export const platformList: { [key: string]: string } = {
  "OTHER": "Other",
  "NES": "NES",
  "SNES": "SNES",
  "N64": "Nintendo 64",
  "GCN": "GameCube",
  "WII": "Wii",
  "WIIU": "Wii U",
  "NSW": "Nintendo Switch",
  "NSW2": "Nintendo Switch 2",
  "GB": "Game Boy",
  "GBC": "Game Boy Color",
  "VB": "Virtual Boy",
  "GBA": "Game Boy Advance",
  "DS": "Nintendo DS",
  "3DS": "Nintendo 3DS",
  "N3DS": "New Nintendo 3DS",
  "PS1": "PlayStation",
  "PS2": "PlayStation 2",
  "PS3": "PlayStation 3",
  "PS4": "PlayStation 4",
  "PS5": "PlayStation 5",
  "PSP": "PlayStation Portable",
  "PSVT": "PlayStation Vita",
  "XBOX": "Original Xbox",
  "X360": "Xbox 360",
  "XBX1": "Xbox One",
  "XBXS": "Xbox Series X|S",
  "SMS": "Sega Master System",
  "SGNS": "Sega Genesis/Mega Drive",
  "STRN": "Sega Saturn",
  "DCST": "Sega Dreamcast",
  "SGG": "Sega Game Gear",
  "PC": "PC Game",
  "STM": "Steam",
};

export const statusList: { [key: string]: string } = {
  "NYP": "Unplayed",
  "UNF": "Unfinished",
  "CPL": "Completed",
  "FPL": "100% Completed",
  "NDL": "Endless",
};